name: mobile_application
description: Mobile application project for group 14(?).

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_storage: ^11.0.5
  cloud_firestore: ^4.0.4

  equatable: ^2.0.0
  cupertino_icons: ^1.0.2
  formz: ^0.4.1
  flutter_riverpod: ^2.1.1
  loading_animation_widget:
  google_sign_in: ^5.4.2
  file_picker: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

#  assets:
    # Images go here
