name: mobile_application
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.0.4
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  equatable: ^2.0.0
  cupertino_icons: ^1.0.2
  formz: ^0.4.1
  flutter_riverpod: ^2.1.1
  loading_animation_widget:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - images/google-logo.png
    - images/facebook-logo.png
