// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9P2QR1j2PfTiBh5JMUKTQK0Ipf0UmlgQ',
    appId: '1:539825877591:android:7be93cbff94360563e6912',
    messagingSenderId: '539825877591',
    projectId: 'mobile-application-proje-901bc',
    storageBucket: 'mobile-application-proje-901bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbcFaJdWzyqoMcJLMf9QoAPKudn9C1Q3Y',
    appId: '1:539825877591:ios:2355de408ed171193e6912',
    messagingSenderId: '539825877591',
    projectId: 'mobile-application-proje-901bc',
    storageBucket: 'mobile-application-proje-901bc.appspot.com',
    androidClientId: '539825877591-390b8tt6d8maoad200oo6p5o6eda1ela.apps.googleusercontent.com',
    iosClientId: '539825877591-j79pjhb54q7p1q2pih72kf4caci5v4pa.apps.googleusercontent.com',
    iosBundleId: 'no.ntnu.mobile-application',
  );
}
